### ISSUE TITLE
Create workflow for publishing Zarf package on new releases

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/leapfrogai-backend-llama-cpp-python#18]
We do not currently have a workflow to build and publish a Zarf package for the backend-llama-cpp-python.

```[tasklist]
### Tasks
- [ ] Workflow for building & publishing Zarf package
```

**Comment by justinthelaw** [comment]
Related to https://github.com/defenseunicorns/leapfrogai-backend-llama-cpp-python/issues/12
