### ISSUE TITLE
llama-cpp-python doesn't use Metal on M2 device by default

### ISSUE THREAD

**Issue by remy415** [defenseunicorns/leapfrogai-backend-llama-cpp-python#7]
I originally deployed this with no modifications. The chat UI worked wonderfully, but was operating at a slower rate. I checked the MacOS Activity Monitor and there was no GPU activity.

I had to install llama-cpp-python on my Mac using the CMAKE_ARGS="-DLLAMA_METAL=on" flag, then use pip download llama-cpp-python to generate a .tar.gz, and change the Dockerfile to copy the zip and pip install it. Once I did that, I built the container again and the GPU acceleration seemed to work.

I tried adding CMAKE_ARGS="-DLLAMA_METAL=on" as an ENV var in the Dockerfile, but I'm somewhat unfamiliar with the cmake environment on my Mac and it generated some library errors.

CMAKE error:
```6.774       Call Stack (most recent call first):
6.774         vendor/llama.cpp/CMakeLists.txt:105 (include)
6.774       
6.774       
6.774       -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
6.774       -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
6.774       -- Found Threads: TRUE
6.774       CMake Error at vendor/llama.cpp/CMakeLists.txt:151 (find_library):
6.774         Could not find FOUNDATION_LIBRARY using the following names: Foundation
6.774       
6.774       
6.774       -- Configuring incomplete, errors occurred!
6.774       
6.774       *** CMake configuration failed
6.774       [end of output]```

**Comment by gphorvath** [comment]
@remy415 bad news I'm afraid. If you want to use Metal GPU you will need to run on host, unless something has changed recently. Here is a quick clip that explains the challenges of virtualizing the Metal GPU: 

https://www.youtube.com/watch?v=Bxa2-wNSjJg&t=307s

**Comment by gphorvath** [comment]
To add, we plan to adapt Tadpole to support host execution:
https://github.com/defenseunicorns/tadpole

This should at least give you a quick way to get up and running with Metal outside of containers. @remy415
